name: Feature request
description: Suggest an idea for this project
title: '[Feature]: '
labels: enhancement
assignees: 'LordDeatHunter'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I am always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to be implemented.
    validations:
      required: true
  - type: textarea
    id: anythingElse
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are requesting!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
